import type { NormalizedEdge, NodeKind, Frontmatter, Diagnostic } from './types/index.js';
import { zeroRange } from './position.js';

export function validate(
  edges: NormalizedEdge[],
  nodeKinds: Map<string, NodeKind>,
  fm: Frontmatter | null,
): Diagnostic[] {
  const diagnostics: Diagnostic[] = [];

  // V001: single-source constraint (Primary Graph)
  const artifactGenerators = new Map<string, string[]>();
  for (const e of edges) {
    if (e.kind === 'output') {
      const gens = artifactGenerators.get(e.artifact) ?? [];
      gens.push(e.process);
      artifactGenerators.set(e.artifact, gens);
    }
  }
  for (const [artifact, processes] of artifactGenerators) {
    if (processes.length > 1) {
      diagnostics.push({ severity: 'error', code: 'V001',
        message: `'${artifact}' generated by multiple processes: ${processes.join(', ')}`,
        range: zeroRange() });
    }
  }

  // V002 / V003: process completeness
  const processInputCount  = new Map<string, number>();
  const processOutputCount = new Map<string, number>();
  for (const [id, kind] of nodeKinds) {
    if (kind === 'process') {
      processInputCount.set(id, 0);
      processOutputCount.set(id, 0);
    }
  }
  for (const e of edges) {
    if (e.kind === 'input' || e.kind === 'feedback') {
      processInputCount.set(e.process, (processInputCount.get(e.process) ?? 0) + 1);
    } else {
      processOutputCount.set(e.process, (processOutputCount.get(e.process) ?? 0) + 1);
    }
  }
  for (const [id, count] of processInputCount) {
    if (count === 0) diagnostics.push({ severity: 'error', code: 'V002',
      message: `Process '${id}' has no inputs`, range: zeroRange() });
  }
  for (const [id, count] of processOutputCount) {
    if (count === 0) diagnostics.push({ severity: 'error', code: 'V003',
      message: `Process '${id}' has no outputs`, range: zeroRange() });
  }

  // V004 / V005 / V006: parts constraints
  const artifactMeta = fm?.artifact ?? {};
  for (const [artifactId, meta] of Object.entries(artifactMeta)) {
    for (const partId of meta.parts ?? []) {
      if (nodeKinds.get(partId) === 'process') {
        diagnostics.push({ severity: 'error', code: 'V004',
          message: `Parts member '${partId}' of '${artifactId}' is a process`,
          range: zeroRange() });
      }
      if (partId === artifactId) {
        diagnostics.push({ severity: 'error', code: 'V005',
          message: `'${artifactId}' cannot include itself in parts`,
          range: zeroRange() });
      }
    }
  }

  // Cycle detection in parts
  const visited = new Set<string>();
  const inStack = new Set<string>();

  function detectCycle(id: string, path: string[]): void {
    if (inStack.has(id)) {
      diagnostics.push({ severity: 'error', code: 'V006',
        message: `Cycle in parts: ${[...path, id].join(' → ')}`,
        range: zeroRange() });
      return;
    }
    if (visited.has(id)) return;
    visited.add(id);
    inStack.add(id);
    for (const part of artifactMeta[id]?.parts ?? []) {
      detectCycle(part, [...path, id]);
    }
    inStack.delete(id);
  }

  for (const id of Object.keys(artifactMeta)) detectCycle(id, []);

  return diagnostics;
}
