import { zeroRange } from "./position.js";
import type {
	Diagnostic,
	Frontmatter,
	NodeKind,
	NormalizedEdge,
} from "./types/index.js";
import { STATUS_VALUES, STYLE_ATTRS } from "./types/index.js";

const STATUS_SET: ReadonlySet<string> = new Set(STATUS_VALUES);
const STYLE_ATTR_SET: ReadonlySet<string> = new Set(STYLE_ATTRS);

export function validate(
	edges: NormalizedEdge[],
	nodeKinds: Map<string, NodeKind>,
	fm: Frontmatter | null,
): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	// V001: single-source constraint (Primary Graph)
	const artifactGenerators = new Map<string, string[]>();
	for (const e of edges) {
		if (e.kind === "output") {
			const gens = artifactGenerators.get(e.artifact) ?? [];
			gens.push(e.process);
			artifactGenerators.set(e.artifact, gens);
		}
	}
	for (const [artifact, processes] of artifactGenerators) {
		if (processes.length > 1) {
			diagnostics.push({
				severity: "error",
				code: "V001",
				message: `'${artifact}' generated by multiple processes: ${processes.join(", ")}`,
				range: zeroRange(),
			});
		}
	}

	// V002 / V003: process completeness — edge参加processのみ (§15.2)
	const processInputCount = new Map<string, number>();
	const processOutputCount = new Map<string, number>();
	for (const e of edges) {
		const p = e.kind === "output" ? e.process : e.process;
		if (!processInputCount.has(p)) {
			processInputCount.set(p, 0);
			processOutputCount.set(p, 0);
		}
	}
	for (const e of edges) {
		if (e.kind === "input" || e.kind === "feedback") {
			processInputCount.set(
				e.process,
				(processInputCount.get(e.process) ?? 0) + 1,
			);
		} else {
			processOutputCount.set(
				e.process,
				(processOutputCount.get(e.process) ?? 0) + 1,
			);
		}
	}
	for (const [id, count] of processInputCount) {
		if (count === 0)
			diagnostics.push({
				severity: "error",
				code: "V002",
				message: `Process '${id}' has no inputs`,
				range: zeroRange(),
			});
	}
	for (const [id, count] of processOutputCount) {
		if (count === 0)
			diagnostics.push({
				severity: "error",
				code: "V003",
				message: `Process '${id}' has no outputs`,
				range: zeroRange(),
			});
	}

	// V004 / V005 / V006: parts constraints
	// V007: artifact.status enum check
	const artifactMeta = fm?.artifact ?? {};
	for (const [artifactId, meta] of Object.entries(artifactMeta)) {
		for (const partId of meta.parts ?? []) {
			if (nodeKinds.get(partId) === "process") {
				diagnostics.push({
					severity: "error",
					code: "V004",
					message: `Parts member '${partId}' of '${artifactId}' is a process`,
					range: zeroRange(),
				});
			}
			if (partId === artifactId) {
				diagnostics.push({
					severity: "error",
					code: "V005",
					message: `'${artifactId}' cannot include itself in parts`,
					range: zeroRange(),
				});
			}
		}
		if (meta.status !== undefined && !STATUS_SET.has(meta.status)) {
			diagnostics.push({
				severity: "error",
				code: "V007",
				message: `Invalid status '${meta.status}' on artifact '${artifactId}'. Allowed: ${STATUS_VALUES.join(", ")}`,
				range: zeroRange(),
			});
		}
	}

	// V008: statusStyles keys must be valid Status enum
	// V009: statusStyles/tagStyles attribute keys must be in STYLE_ATTRS
	for (const [key, style] of Object.entries(fm?.statusStyles ?? {})) {
		if (!STATUS_SET.has(key)) {
			diagnostics.push({
				severity: "error",
				code: "V008",
				message: `Invalid statusStyles key '${key}'. Allowed: ${STATUS_VALUES.join(", ")}`,
				range: zeroRange(),
			});
		}
		for (const attr of Object.keys(style ?? {})) {
			if (!STYLE_ATTR_SET.has(attr)) {
				diagnostics.push({
					severity: "error",
					code: "V009",
					message: `Invalid style attribute '${attr}' in statusStyles.${key}. Allowed: ${STYLE_ATTRS.join(", ")}`,
					range: zeroRange(),
				});
			}
		}
	}
	for (const [key, style] of Object.entries(fm?.tagStyles ?? {})) {
		for (const attr of Object.keys(style ?? {})) {
			if (!STYLE_ATTR_SET.has(attr)) {
				diagnostics.push({
					severity: "error",
					code: "V009",
					message: `Invalid style attribute '${attr}' in tagStyles.${key}. Allowed: ${STYLE_ATTRS.join(", ")}`,
					range: zeroRange(),
				});
			}
		}
	}

	const visited = new Set<string>();
	const inStack = new Set<string>();
	const path: string[] = [];

	function detectCycle(id: string): void {
		if (inStack.has(id)) {
			diagnostics.push({
				severity: "error",
				code: "V006",
				message: `Cycle in parts: ${[...path, id].join(" → ")}`,
				range: zeroRange(),
			});
			return;
		}
		if (visited.has(id)) return;
		visited.add(id);
		inStack.add(id);
		path.push(id);
		for (const part of artifactMeta[id]?.parts ?? []) detectCycle(part);
		path.pop();
		inStack.delete(id);
	}

	for (const id of Object.keys(artifactMeta)) detectCycle(id);

	return diagnostics;
}
