import { zeroRange } from "./position.js";
import type {
	Diagnostic,
	Frontmatter,
	NodeKind,
	NormalizedEdge,
} from "./types/index.js";
import { STATUS_VALUES, STYLE_ATTRS } from "./types/index.js";

const STATUS_SET: ReadonlySet<string> = new Set(STATUS_VALUES);
const STYLE_ATTR_SET: ReadonlySet<string> = new Set(STYLE_ATTRS);

export interface ValidateOptions {
	strict?: boolean;
}

export function validate(
	edges: NormalizedEdge[],
	nodeKinds: Map<string, NodeKind>,
	fm: Frontmatter | null,
	options?: ValidateOptions,
): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];

	// V001: single-source constraint (Primary Graph)
	const artifactGenerators = new Map<string, string[]>();
	for (const e of edges) {
		if (e.kind === "output") {
			const gens = artifactGenerators.get(e.artifact) ?? [];
			gens.push(e.process);
			artifactGenerators.set(e.artifact, gens);
		}
	}
	for (const [artifact, processes] of artifactGenerators) {
		if (processes.length > 1) {
			diagnostics.push({
				severity: "error",
				code: "V001",
				message: `'${artifact}' generated by multiple processes: ${processes.join(", ")}`,
				range: zeroRange(),
			});
		}
	}

	// V002 / V003: process completeness — edge参加processのみ (§15.2)
	const processInputCount = new Map<string, number>();
	const processOutputCount = new Map<string, number>();
	for (const e of edges) {
		if (!processInputCount.has(e.process)) processInputCount.set(e.process, 0);
		if (!processOutputCount.has(e.process))
			processOutputCount.set(e.process, 0);
		if (e.kind === "input" || e.kind === "feedback") {
			processInputCount.set(
				e.process,
				(processInputCount.get(e.process) ?? 0) + 1,
			);
		} else {
			processOutputCount.set(
				e.process,
				(processOutputCount.get(e.process) ?? 0) + 1,
			);
		}
	}
	for (const [id, count] of processInputCount) {
		if (count === 0)
			diagnostics.push({
				severity: "error",
				code: "V002",
				message: `Process '${id}' has no inputs`,
				range: zeroRange(),
			});
	}
	for (const [id, count] of processOutputCount) {
		if (count === 0)
			diagnostics.push({
				severity: "error",
				code: "V003",
				message: `Process '${id}' has no outputs`,
				range: zeroRange(),
			});
	}

	// V020: frontmatter-declared process with no edges at all (orphaned process)
	for (const pid of Object.keys(fm?.process ?? {})) {
		if (!processInputCount.has(pid)) {
			diagnostics.push({
				severity: "error",
				code: "V020",
				message: `Process '${pid}' is declared but has no edges (orphaned process)`,
				range: zeroRange(),
			});
		}
	}

	// V004 / V005 / V006: parts constraints
	// V007: artifact.status enum check
	// W001: parts member without edges
	const artifactMeta = fm?.artifact ?? {};

	// Collect all artifact/process ids that appear in at least one edge
	const nodesWithEdges = new Set<string>();
	for (const e of edges) {
		if (e.kind === "input" || e.kind === "feedback") {
			nodesWithEdges.add(e.artifact);
			nodesWithEdges.add(e.process);
		} else {
			nodesWithEdges.add(e.process);
			nodesWithEdges.add(e.artifact);
		}
	}

	for (const [artifactId, meta] of Object.entries(artifactMeta)) {
		for (const partId of meta.parts ?? []) {
			if (nodeKinds.get(partId) === "process") {
				diagnostics.push({
					severity: "error",
					code: "V004",
					message: `Parts member '${partId}' of '${artifactId}' is a process`,
					range: zeroRange(),
				});
			}
			if (partId === artifactId) {
				diagnostics.push({
					severity: "error",
					code: "V005",
					message: `'${artifactId}' cannot include itself in parts`,
					range: zeroRange(),
				});
			}
			// W001: parts member with no edges (§17.4: should be input to a merge process)
			if (!nodesWithEdges.has(partId) && nodeKinds.get(partId) !== "process") {
				diagnostics.push({
					severity: "warning",
					code: "W001",
					message: `Parts member '${partId}' of '${artifactId}' has no edges`,
					range: zeroRange(),
				});
			}
		}
		if (meta.status !== undefined && !STATUS_SET.has(meta.status)) {
			diagnostics.push({
				severity: "error",
				code: "V007",
				message: `Invalid status '${meta.status}' on artifact '${artifactId}'. Allowed: ${STATUS_VALUES.join(", ")}`,
				range: zeroRange(),
			});
		}
	}

	// V008: statusStyles keys must be valid Status enum
	// V009: statusStyles / tag.<id>.style attribute keys must be in STYLE_ATTRS
	for (const [key, style] of Object.entries(fm?.statusStyles ?? {})) {
		if (!STATUS_SET.has(key)) {
			diagnostics.push({
				severity: "error",
				code: "V008",
				message: `Invalid statusStyles key '${key}'. Allowed: ${STATUS_VALUES.join(", ")}`,
				range: zeroRange(),
			});
		}
		for (const attr of Object.keys(style ?? {})) {
			if (!STYLE_ATTR_SET.has(attr)) {
				diagnostics.push({
					severity: "error",
					code: "V009",
					message: `Invalid style attribute '${attr}' in statusStyles.${key}. Allowed: ${STYLE_ATTRS.join(", ")}`,
					range: zeroRange(),
				});
			}
		}
	}
	for (const [key, meta] of Object.entries(fm?.tag ?? {})) {
		for (const attr of Object.keys(meta?.style ?? {})) {
			if (!STYLE_ATTR_SET.has(attr)) {
				diagnostics.push({
					severity: "error",
					code: "V009",
					message: `Invalid style attribute '${attr}' in tag.${key}.style. Allowed: ${STYLE_ATTRS.join(", ")}`,
					range: zeroRange(),
				});
			}
		}
	}

	const visited = new Set<string>();
	const inStack = new Set<string>();
	const path: string[] = [];

	function detectCycle(id: string): void {
		if (inStack.has(id)) {
			diagnostics.push({
				severity: "error",
				code: "V006",
				message: `Cycle in parts: ${[...path, id].join(" → ")}`,
				range: zeroRange(),
			});
			return;
		}
		if (visited.has(id)) return;
		visited.add(id);
		inStack.add(id);
		path.push(id);
		for (const part of artifactMeta[id]?.parts ?? []) detectCycle(part);
		path.pop();
		inStack.delete(id);
	}

	for (const id of Object.keys(artifactMeta)) detectCycle(id);

	// V010: primary-graph cycle detection
	// Build adjacency map from primary edges only (feedback edges are exempt)
	const primaryAdj = new Map<string, string[]>();
	for (const e of edges) {
		if (e.kind === "input") {
			// artifact -> process
			const adj = primaryAdj.get(e.artifact) ?? [];
			adj.push(e.process);
			primaryAdj.set(e.artifact, adj);
		} else if (e.kind === "output") {
			// process -> artifact
			const adj = primaryAdj.get(e.process) ?? [];
			adj.push(e.artifact);
			primaryAdj.set(e.process, adj);
		}
	}
	{
		const color = new Map<string, "white" | "gray" | "black">();
		const allNodes = new Set<string>();
		for (const e of edges) {
			if (e.kind !== "feedback") {
				allNodes.add(e.kind === "output" ? e.process : e.artifact);
				allNodes.add(e.kind === "output" ? e.artifact : e.process);
			}
		}
		for (const n of allNodes) color.set(n, "white");

		let cycleReported = false;
		function dfsV010(id: string): boolean {
			if (color.get(id) === "gray") return true;
			if (color.get(id) === "black") return false;
			color.set(id, "gray");
			for (const neighbor of primaryAdj.get(id) ?? []) {
				if (dfsV010(neighbor)) {
					if (!cycleReported) {
						cycleReported = true;
						diagnostics.push({
							severity: "error",
							code: "V010",
							message: `Primary graph contains a cycle involving '${id}' → '${neighbor}'`,
							range: zeroRange(),
						});
					}
					color.set(id, "black");
					return false;
				}
			}
			color.set(id, "black");
			return false;
		}
		for (const n of allNodes) {
			if (color.get(n) === "white") dfsV010(n);
		}
	}

	// V011: strict-mode feedback validation
	// In strict mode, for each feedback edge A >>? P, verify that P can reach A
	// in the primary graph (P directly or transitively produces A).
	if (options?.strict) {
		// Build reverse adjacency for reachability: from a process, what artifacts can be reached?
		function primaryReachable(startProcess: string): Set<string> {
			const reachable = new Set<string>();
			const queue: string[] = [startProcess];
			while (queue.length > 0) {
				const node = queue.shift()!;
				for (const neighbor of primaryAdj.get(node) ?? []) {
					if (!reachable.has(neighbor)) {
						reachable.add(neighbor);
						queue.push(neighbor);
					}
				}
			}
			return reachable;
		}

		for (const e of edges) {
			if (e.kind === "feedback") {
				const reachable = primaryReachable(e.process);
				if (!reachable.has(e.artifact)) {
					diagnostics.push({
						severity: "error",
						code: "V011",
						message: `Feedback artifact '${e.artifact}' is not reachable from process '${e.process}' in the primary graph`,
						range: zeroRange(),
					});
				}
			}
		}
	}

	// W002: artifact without criteria
	// V012: criteria on process
	// V013: location on process
	// V014: command on artifact
	// V015: revises on process
	const processMeta = fm?.process ?? {};
	for (const [pid, meta] of Object.entries(processMeta)) {
		const m = meta as Record<string, unknown>;
		if (m.criteria !== undefined) {
			diagnostics.push({
				severity: "error",
				code: "V012",
				message: `'criteria' is not allowed on process '${pid}'`,
				range: zeroRange(),
			});
		}
		if (m.location !== undefined) {
			diagnostics.push({
				severity: "error",
				code: "V013",
				message: `'location' is not allowed on process '${pid}'`,
				range: zeroRange(),
			});
		}
		if (m.revises !== undefined) {
			diagnostics.push({
				severity: "error",
				code: "V015",
				message: `'revises' is not allowed on process '${pid}'`,
				range: zeroRange(),
			});
		}
	}
	for (const [aid, meta] of Object.entries(artifactMeta)) {
		if (meta.criteria === undefined) {
			diagnostics.push({
				severity: options?.strict ? "error" : "warning",
				code: "W002",
				message: `Artifact '${aid}' has no 'criteria' field`,
				range: zeroRange(),
			});
		}
		if ((meta as Record<string, unknown>).command !== undefined) {
			diagnostics.push({
				severity: "error",
				code: "V014",
				message: `'command' is not allowed on artifact '${aid}'`,
				range: zeroRange(),
			});
		}
	}

	// V016: revises target not found
	// V017: revises self-reference
	// V018: revises branching (multiple artifacts revise same target)
	// V019: revises cycle
	const revisesTargets = new Map<string, string>(); // aid -> target
	for (const [aid, meta] of Object.entries(artifactMeta)) {
		const target = meta.revises as unknown;
		if (target === undefined || target === null) continue;
		if (typeof target !== "string") {
			diagnostics.push({
				severity: "error",
				code: "V016",
				message: `'revises' on artifact '${aid}' must be a string, got ${typeof target}`,
				range: zeroRange(),
			});
			continue;
		}
		if (target === aid) {
			diagnostics.push({
				severity: "error",
				code: "V017",
				message: `Artifact '${aid}' revises itself`,
				range: zeroRange(),
			});
			continue;
		}
		if (artifactMeta[target] === undefined) {
			diagnostics.push({
				severity: "error",
				code: "V016",
				message: `'revises' target '${target}' of artifact '${aid}' not found in this file`,
				range: zeroRange(),
			});
			continue;
		}
		revisesTargets.set(aid, target);
	}

	// V018: branching — multiple artifacts revise the same target
	const revisedBy = new Map<string, string[]>();
	for (const [aid, target] of revisesTargets) {
		const arr = revisedBy.get(target) ?? [];
		arr.push(aid);
		revisedBy.set(target, arr);
	}
	for (const [target, revisors] of revisedBy) {
		if (revisors.length > 1) {
			diagnostics.push({
				severity: "error",
				code: "V018",
				message: `Artifact '${target}' is revised by multiple artifacts: ${revisors.join(", ")}`,
				range: zeroRange(),
			});
		}
	}

	// V019: cycle in revises chain
	{
		const color = new Map<string, "white" | "gray" | "black">();
		for (const id of Object.keys(artifactMeta)) color.set(id, "white");
		function dfsRevises(id: string): boolean {
			if (color.get(id) === "gray") return true;
			if (color.get(id) === "black") return false;
			color.set(id, "gray");
			const target = revisesTargets.get(id);
			if (target !== undefined && dfsRevises(target)) {
				diagnostics.push({
					severity: "error",
					code: "V019",
					message: `Cycle detected in 'revises' chain involving '${id}'`,
					range: zeroRange(),
				});
				color.set(id, "black");
				return false;
			}
			color.set(id, "black");
			return false;
		}
		for (const id of Object.keys(artifactMeta)) {
			if (color.get(id) === "white") dfsRevises(id);
		}
	}

	// W003: status non-monotonicity
	// For each process: if any output artifact has status 'done',
	// all normal input artifacts with explicit status must also be 'done'
	{
		const processInputs = new Map<string, string[]>();
		const processOutputs = new Map<string, string[]>();
		for (const e of edges) {
			if (e.kind === "input") {
				const arr = processInputs.get(e.process) ?? [];
				arr.push(e.artifact);
				processInputs.set(e.process, arr);
			} else if (e.kind === "output") {
				const arr = processOutputs.get(e.process) ?? [];
				arr.push(e.artifact);
				processOutputs.set(e.process, arr);
			}
		}
		for (const [pid, outputs] of processOutputs) {
			const hasDoneOutput = outputs.some(
				(aid) => artifactMeta[aid]?.status === "done",
			);
			if (!hasDoneOutput) continue;
			for (const aid of processInputs.get(pid) ?? []) {
				const status = artifactMeta[aid]?.status;
				if (status !== undefined && status !== "done") {
					diagnostics.push({
						severity: "warning",
						code: "W003",
						message: `Process '${pid}' outputs a 'done' artifact but input '${aid}' has status '${status}'`,
						range: zeroRange(),
					});
				}
			}
		}
	}

	// V023: subflow on artifact
	for (const [id, meta] of Object.entries(fm?.artifact ?? {})) {
		if ((meta as Record<string, unknown>).subflow !== undefined) {
			diagnostics.push({
				severity: "error",
				code: "V023",
				message: `'subflow' is not allowed on artifact '${id}'`,
				range: zeroRange(),
			});
		}
	}

	// V024: boundary without subflow
	for (const [pid, meta] of Object.entries(fm?.process ?? {})) {
		if (
			(meta as Record<string, unknown>).boundary !== undefined &&
			meta.subflow === undefined
		) {
			diagnostics.push({
				severity: "error",
				code: "V024",
				message: `'boundary' on process '${pid}' requires 'subflow'`,
				range: zeroRange(),
			});
		}
	}

	// V025: cycle in group parent chain
	{
		const groupMeta = fm?.group ?? {};
		const color = new Map<string, "white" | "gray" | "black">();
		for (const id of Object.keys(groupMeta)) color.set(id, "white");

		function dfsGroup(id: string): boolean {
			color.set(id, "gray");
			const parent = groupMeta[id]?.parent;
			if (parent !== undefined) {
				if (color.get(parent) === "gray") {
					diagnostics.push({
						severity: "error",
						code: "V025",
						message: `Cycle detected in 'parent' chain involving group '${id}' → '${parent}'`,
						range: zeroRange(),
					});
					color.set(id, "black");
					return true;
				}
				if (color.get(parent) === "white") {
					if (dfsGroup(parent)) {
						color.set(id, "black");
						return true;
					}
				}
			}
			color.set(id, "black");
			return false;
		}
		for (const id of Object.keys(groupMeta)) {
			if (color.get(id) === "white") dfsGroup(id);
		}
	}

	return diagnostics;
}
