import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

import {
	addGeneratedMarkdownNotice,
	addGeneratedSourceComment,
	agentToCodexToml,
	buildCodexPluginManifest,
	buildCodexProjectConfig,
	claudeHooksToCodexHooks,
	claudeInstructionsToAgents,
	claudeRootInstructionsToAgents,
	commandToCodexSkill,
} from "./gen-codex-assets.mjs";
import { DISTRIBUTED_COMMANDS } from "./harness-inventory.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function parseTomlDeveloperInstructions(source) {
	const match = source.match(/^developer_instructions = """([\s\S]*)"""\n$/m);
	assert.ok(match, "expected a multiline TOML developer_instructions value");
	const encoded = match[1].startsWith("\n") ? match[1].slice(1) : match[1];
	const escapes = { b: "\b", f: "\f", n: "\n", r: "\r", t: "\t" };

	return encoded.replace(/\\([\\"bfnrt])/g, (_escape, character) => {
		if (character === "\\" || character === '"') return character;
		return escapes[character];
	});
}

describe("buildCodexPluginManifest", () => {
	it("emits the native Codex manifest shape without a hooks field", () => {
		assert.deepEqual(
			buildCodexPluginManifest({ version: "1.2.3", description: "x" }),
			{
				name: "pfdsl",
				version: "1.2.3",
				description: "x",
				author: { name: "takasek" },
				homepage: "https://github.com/takasek/pfdsl",
				repository: "https://github.com/takasek/pfdsl",
				license: "MIT",
				skills: "./skills/",
				interface: {
					displayName: "pfdsl",
					shortDescription: "x",
					longDescription: "x",
					developerName: "takasek",
					category: "Developer Tools",
					capabilities: ["Skills"],
					defaultPrompt: ["Use pfd-ops to operate this project."],
				},
			},
		);
	});
});

describe("generated ownership notices", () => {
	it("preserves an existing Markdown notice after frontmatter", () => {
		const source =
			"---\nname: generated\n---\n" +
			"<!-- DO NOT EDIT. Authoritative source: docs/quality-guide.md. -->\n\n" +
			"body\n";

		assert.equal(
			addGeneratedMarkdownNotice(source, ".claude/skills/pfdsl/SKILL.md"),
			source,
		);
	});

	it("preserves an existing Markdown heading notice with an em dash", () => {
		const source =
			"---\n" +
			"# DO NOT EDIT — generated by scripts/gen-skill.mjs. Authoritative source: https://example.test/SKILL.md\n" +
			"name: generated\n---\nbody\n";

		assert.equal(
			addGeneratedMarkdownNotice(source, ".claude/skills/pfdsl/SKILL.md"),
			source,
		);
	});

	it("preserves an existing Markdown snapshot comment with an em dash", () => {
		const source =
			"<!-- DO NOT EDIT — snapshot. Authoritative source: https://example.test/quality-guide.md -->\n\n" +
			"body\n";

		assert.equal(
			addGeneratedMarkdownNotice(source, ".claude/skills/pfdsl/SKILL.md"),
			source,
		);
	});

	it("adds a Markdown notice when the source has none", () => {
		assert.equal(
			addGeneratedMarkdownNotice("body\n", ".claude/skills/pfd-ops/SKILL.md"),
			"<!-- DO NOT EDIT. Authoritative source: .claude/skills/pfd-ops/SKILL.md. -->\n\nbody\n",
		);
	});

	it("preserves an existing JavaScript notice after a shebang", () => {
		const source =
			"#!/usr/bin/env node\n" +
			"// DO NOT EDIT. Authoritative source: docs/quality-guide.mjs.\n" +
			"console.log('body');\n";

		assert.equal(
			addGeneratedSourceComment(source, ".claude/skills/pfd-ops/script.mjs"),
			source,
		);
	});

	it("preserves an existing JavaScript notice with an em dash", () => {
		const source =
			"// DO NOT EDIT — generated. Authoritative source: https://example.test/script.mjs\n" +
			"console.log('body');\n";

		assert.equal(
			addGeneratedSourceComment(source, ".claude/skills/pfd-ops/script.mjs"),
			source,
		);
	});
});

describe("commandToCodexSkill", () => {
	it("converts every maintained command argument clause without leaving a Claude placeholder", () => {
		const expectedInstructions = new Map([
			[
				"pfd-cycle.md",
				"ユーザーがスキル呼び出しとともに指定した内容があれば、作業選択の指定として扱う。",
			],
			[
				"pfd-init.md",
				"ユーザーがスキル呼び出しとともに指定した内容があれば、引数として扱う。",
			],
			[
				"pfd-retro.md",
				"ユーザーがスキル呼び出しとともに指定した内容があれば、監査対象範囲の指定として扱う。",
			],
		]);

		for (const sourcePath of DISTRIBUTED_COMMANDS) {
			const output = commandToCodexSkill(
				sourcePath,
				readFileSync(resolve(root, ".claude/commands", sourcePath), "utf-8"),
			);
			assert.doesNotMatch(output, /\$ARGUMENTS/, sourcePath);
			assert.match(
				output,
				new RegExp(expectedInstructions.get(sourcePath)),
				sourcePath,
			);
		}
	});

	it("rejects an unrecognized Claude argument construct with its source path", () => {
		const source =
			"---\n" +
			"description: x\n" +
			"---\n\n" +
			"Unsupported argument form: $ARGUMENTS\n";

		assert.throws(
			() => commandToCodexSkill("pfd-unknown.md", source),
			/pfd-unknown\.md.*\$ARGUMENTS/,
		);
	});

	it("preserves the command body except for the Codex argument instruction", () => {
		const source =
			"---\n" +
			"description: Choose the next PFD task.\n" +
			"---\n\n" +
			"Keep this body verbatim.\n\n" +
			"引数（あれば作業選択の指定として扱う）: $ARGUMENTS\n";

		assert.equal(
			commandToCodexSkill("pfd-cycle.md", source),
			"---\n" +
				"name: pfd-cycle\n" +
				"description: Choose the next PFD task.\n" +
				"---\n" +
				"<!-- DO NOT EDIT. Authoritative source: .claude/commands/pfd-cycle.md. -->\n\n" +
				"Keep this body verbatim.\n\n" +
				"ユーザーがスキル呼び出しとともに指定した内容があれば、作業選択の指定として扱う。\n",
		);
	});

	it("uses an assembly-supplied non-colliding output name while retaining the real source path for errors", () => {
		const source = "---\ndescription: Run the retrospective.\n---\n\nbody\n";

		assert.match(
			commandToCodexSkill("pfd-retro.md", source, "source-command-pfd-retro"),
			/^name: source-command-pfd-retro$/m,
		);

		assert.throws(
			() =>
				commandToCodexSkill(
					"pfd-retro.md",
					"---\nextra: unsupported\n---\n\nbody\n",
					"source-command-pfd-retro",
				),
			/pfd-retro\.md.*extra/,
		);
	});

	it("rejects unknown command frontmatter with its source path and key", () => {
		const source = "---\ndescription: x\nextra: y\n---\n\nbody\n";

		assert.throws(
			() => commandToCodexSkill("pfd-cycle.md", source),
			/pfd-cycle\.md.*extra/,
		);
	});
});

describe("agentToCodexToml", () => {
	it("maps pfd-lens's known read-only tools without selecting a Codex model", () => {
		const source = readFileSync(
			resolve(root, ".claude/agents/pfd-lens.md"),
			"utf-8",
		);
		const output = agentToCodexToml("pfd-lens.md", source);

		assert.match(output, /^description = /m);
		assert.match(output, /^name = "pfd-lens"$/m);
		assert.match(output, /^sandbox_mode = "read-only"$/m);
		assert.doesNotMatch(output, /^model = /m);
		assert.match(output, /^developer_instructions = """/m);
		assert.match(output, /\.agents\/skills\/pfd-retro\/SKILL\.md/);
		assert.match(output, /\$\{PLUGIN_ROOT\}/);
	});

	it("maps pfd-implementer's known write tools and repository instructions", () => {
		const source = readFileSync(
			resolve(root, ".claude/agents/pfd-implementer.md"),
			"utf-8",
		);
		const output = agentToCodexToml("pfd-implementer.md", source);

		assert.match(output, /^sandbox_mode = "workspace-write"$/m);
		assert.match(
			output,
			/^# DO NOT EDIT\. Authoritative source: \.claude\/agents\/pfd-implementer\.md\.$/m,
		);
		assert.match(output, /`AGENTS\.md`/);
		assert.match(
			output,
			/親 agent が `git fetch`、stage、commit、`git push`、PR の作成・更新、issue の作成・クローズ・コメントを担当する。/,
		);
		assert.match(
			output,
			/権限エラーはユーザーへ直接継続を求めず、親 agent へ引き上げる。/,
		);
		assert.match(output, /この節は本文中の git に関する指示より優先する。/);
	});

	it("keeps the Codex-only git boundary when Claude's pfd-implementer wording changes", () => {
		const source =
			"---\n" +
			"name: pfd-implementer\n" +
			"description: Delegate settled implementation work.\n" +
			"tools: Bash, Read, Edit, Write, Grep, Glob, Skill\n" +
			"model: sonnet\n" +
			"---\n\n" +
			"The upstream wording may change without changing this Codex boundary.\n";

		const output = agentToCodexToml("pfd-implementer.md", source);

		assert.match(
			output,
			/親 agent が `git fetch`、stage、commit、`git push`、PR の作成・更新、issue の作成・クローズ・コメントを担当する。/,
		);
		assert.match(
			output,
			/subagent は worktree 内のファイル編集とテスト・検査だけを担当する。/,
		);
	});

	it("rejects an absent or blank agent name", () => {
		for (const name of [undefined, "   "]) {
			const nameLine = name === undefined ? "" : `name: ${name}\n`;
			const source =
				"---\n" +
				nameLine +
				"description: x\ntools: Read, Grep, Bash\nmodel: sonnet\n---\n\nbody\n";

			assert.throws(
				() => agentToCodexToml("pfd.md", source),
				/pfd\.md.*name.*non-empty string/,
			);
		}
	});

	it("preserves the transformed body through TOML multiline string parsing", () => {
		const body = [
			"",
			"leading newline",
			String.raw`literal \\n literal \\t literal \\" literal \\u1234`,
			'quotes " and triple """',
			"",
		].join("\n");
		const source =
			"---\n" +
			"name: pfd\n" +
			"description: x\n" +
			"tools: Read, Grep, Bash\n" +
			"model: sonnet\n" +
			"---\n" +
			body;

		const output = agentToCodexToml("pfd.md", source);

		assert.equal(parseTomlDeveloperInstructions(output), body);
	});

	it("rejects an unsupported model with its source path and key", () => {
		const source =
			"---\nname: pfd\ndescription: x\ntools: Read, Grep, Bash\nmodel: opus\n---\n\nbody\n";

		assert.throws(() => agentToCodexToml("pfd.md", source), /pfd\.md.*model/);
	});

	it("rejects an unsupported tools list with its source path and key", () => {
		const source =
			"---\nname: pfd\ndescription: x\ntools: Read\nmodel: sonnet\n---\n\nbody\n";

		assert.throws(() => agentToCodexToml("pfd.md", source), /pfd\.md.*tools/);
	});

	it("rejects unknown agent frontmatter with its source path and key", () => {
		const source =
			"---\n" +
			"name: pfd\n" +
			"description: x\n" +
			"tools: Read, Grep, Bash\n" +
			"model: sonnet\n" +
			"extra: y\n" +
			"---\n\nbody\n";

		assert.throws(() => agentToCodexToml("pfd.md", source), /pfd\.md.*extra/);
	});
});

describe("claudeInstructionsToAgents", () => {
	it("replaces the approved repository paths and Codex-specific instructions", () => {
		const source =
			"CLAUDE.md\n" +
			"CLAUDE_PLUGIN_ROOT\n" +
			".claude/skills/pfd-ops/SKILL.md\n" +
			`\${CLAUDE_PLUGIN_ROOT}/skills/pfd-ops/SKILL.md\n` +
			"Claude 向け指示\n" +
			"Claude へ恒常的に届ける\n" +
			"1つの Claude Code plugin\n" +
			"を Claude Code プラットフォーム側\n" +
			".Codex/settings.json\n" +
			".claude/settings.json\n" +
			"unchanged\n";

		assert.equal(
			claudeInstructionsToAgents(source),
			"AGENTS.md\n" +
				"PLUGIN_ROOT\n" +
				".agents/skills/pfd-ops/SKILL.md\n" +
				`\${PLUGIN_ROOT}/skills/pfd-ops/SKILL.md\n` +
				"Codex 向け指示\n" +
				"Codex へ恒常的に届ける\n" +
				"Claude Code と Codex の両方で使える plugin\n" +
				"を各ハーネスのプラットフォーム側\n" +
				".codex/hooks.json\n" +
				".codex/hooks.json\n" +
				"unchanged\n",
		);
	});
});

describe("claudeRootInstructionsToAgents", () => {
	it("adds Codex-only parent ownership for git metadata operations", () => {
		const output = claudeRootInstructionsToAgents("Read CLAUDE.md.\n");

		assert.match(
			output,
			/^<!-- DO NOT EDIT\. Authoritative source: CLAUDE\.md\. -->$/m,
		);
		assert.match(output, /^Read AGENTS\.md\.$/m);
		assert.match(
			output,
			/親 agent が `git fetch`、stage、commit、`git push`、PR の作成・更新、issue の作成・クローズ・コメントを担当する。/,
		);
		assert.match(
			output,
			/subagent は git metadata 操作や外部公開操作を実行しない。/,
		);
	});
});

describe("buildCodexProjectConfig", () => {
	it("uses the least-privilege trusted-project sandbox and registry network access", () => {
		assert.equal(
			buildCodexProjectConfig(),
			'# DO NOT EDIT. Authoritative source: scripts/lib/gen-codex-assets.mjs.\n\nsandbox_mode = "workspace-write"\napproval_policy = "on-request"\n\n[sandbox_workspace_write]\nnetwork_access = true\n',
		);
	});
});

describe("Codex generated-file attributes", () => {
	it("marks generated Codex outputs while leaving their maintained sources unclassified", () => {
		const output = execFileSync(
			"git",
			[
				"check-attr",
				"linguist-generated",
				"--",
				"AGENTS.md",
				".agents/skills/pfd-ops/SKILL.md",
				".codex/agents/pfd-implementer.toml",
				".codex/config.toml",
				".codex/GENERATED.md",
				".codex/hooks.json",
				"plugin/pfdsl-codex/skills/pfd-ops/SKILL.md",
				"CLAUDE.md",
				".claude/agents/pfd-implementer.md",
				".claude/settings.json",
				"hooks/retro-reminder-post-tool-use.mjs",
			],
			{ cwd: root, encoding: "utf-8" },
		);
		const attributes = new Map(
			output
				.trim()
				.split("\n")
				.map((line) => {
					const [path, , value] = line.split(": ");
					return [path, value];
				}),
		);

		for (const path of [
			"AGENTS.md",
			".agents/skills/pfd-ops/SKILL.md",
			".codex/agents/pfd-implementer.toml",
			".codex/config.toml",
			".codex/GENERATED.md",
			".codex/hooks.json",
			"plugin/pfdsl-codex/skills/pfd-ops/SKILL.md",
		]) {
			assert.equal(attributes.get(path), "true", path);
		}
		for (const path of [
			"CLAUDE.md",
			".claude/agents/pfd-implementer.md",
			".claude/settings.json",
			"hooks/retro-reminder-post-tool-use.mjs",
		]) {
			assert.equal(attributes.get(path), "unspecified", path);
		}
	});
});

describe("claudeHooksToCodexHooks", () => {
	it("copies only the hooks object", () => {
		const settings = JSON.stringify({
			permissions: { allow: ["Bash(node scripts/*)"] },
			hooks: { PreToolUse: [{ matcher: "Bash", hooks: [] }] },
		});

		assert.deepEqual(JSON.parse(claudeHooksToCodexHooks(settings)), {
			hooks: { PreToolUse: [{ matcher: "Bash", hooks: [] }] },
		});
	});
});
