// The provenance header stamped onto the generated pfdsl SKILL.md.
//
// It is injected here rather than kept as literal line 2 of the template so the
// template — the file maintainers are actually supposed to edit — does not warn
// against editing itself (#678).
//
// The header points at one exact file by blob URL, which a probe found easier
// to act on than a directory-only pointer. That form is available here because
// this output has a single source; the aggregating outputs (examples.md,
// samples.md) are many-to-one and cannot adopt it unchanged, so this is not yet
// a repo-wide rule — unifying the header formats is tracked in #678.
// It deliberately carries no regeneration command: that is upstream-only
// information and has no meaning in a repo that consumes the plugin (#674).
// Upstream keeps the command in scripts/skill-template/CLAUDE.md.
export const SKILL_HEADER =
	"# DO NOT EDIT — generated by scripts/gen-skill.mjs. Authoritative source: https://github.com/takasek/pfdsl/blob/main/scripts/skill-template/SKILL.md";

/**
 * Insert the provenance header as the first line inside the template's YAML
 * frontmatter. The header must live inside the frontmatter (as a `#` comment)
 * because a comment above it would terminate the frontmatter block.
 *
 * Requiring both delimiters is what makes the DO NOT EDIT guard below sound:
 * scanning to end-of-file when the closing `---` is missing would search the
 * whole document, so a body mention of the phrase would read as a header.
 *
 * Line endings are taken from the document rather than assumed: a Windows
 * checkout (core.autocrlf=true, and .gitattributes pins no eol here) delivers
 * CRLF, and the injected line has to match or the file ends up mixed (#644).
 *
 * @param {string} templateSrc contents of scripts/skill-template/SKILL.md
 * @returns {string} the same document with the header inserted
 */
export function injectGeneratedHeader(templateSrc) {
	const frontmatter = templateSrc.match(/^---(\r?\n)([\s\S]*?\r?\n)---\r?\n/);
	if (!frontmatter) {
		throw new Error(
			"skill template must start with a YAML frontmatter block ('---')",
		);
	}
	if (/DO NOT EDIT/.test(frontmatter[2])) {
		throw new Error(
			"skill template must not carry a DO NOT EDIT header — it is injected by scripts/lib/skill-header.mjs at generation time",
		);
	}
	const open = `---${frontmatter[1]}`;
	return `${open}${SKILL_HEADER}${frontmatter[1]}${templateSrc.slice(open.length)}`;
}
