[package]
name = "pfdsl-prototype"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "pfdsl_prototype"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

[dependencies]
tauri = { version = "~2.11", features = [] }
serde = { version = "1", features = ["derive"] }
roxmltree = "0.20"
tokio = { version = "1", features = ["sync"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
