import { zeroRange } from "../position.js";
import type { Diagnostic } from "../types/index.js";
import type { RuleContext } from "./context.js";

/** V001: an artifact may be generated by at most one process (§15.1). */
export function singleSource(ctx: RuleContext): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];
	for (const [artifact, processes] of ctx.edgeGroups.artifactProducers) {
		if (processes.length > 1) {
			diagnostics.push({
				severity: "error",
				code: "V001",
				message: `'${artifact}' generated by multiple processes: ${processes.join(", ")}`,
				range: zeroRange(),
			});
		}
	}
	return diagnostics;
}

/**
 * V002 / V003: a process on the graph needs inputs and outputs (§15.2).
 * Feedback edges count as inputs; only `->` edges count as outputs. A process
 * on no edge at all is out of scope here — that is V020.
 */
export function processCompleteness(ctx: RuleContext): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];
	const { processInputs, processOutputs, processFeedback } = ctx.edgeGroups;
	for (const pid of ctx.edgeProcesses) {
		const inputs =
			(processInputs.get(pid)?.length ?? 0) +
			(processFeedback.get(pid)?.length ?? 0);
		if (inputs === 0) {
			diagnostics.push({
				severity: ctx.strictly("warning"),
				code: "V002",
				message: `Process '${pid}' has no inputs`,
				range: zeroRange(),
			});
		}
	}
	for (const pid of ctx.edgeProcesses) {
		if ((processOutputs.get(pid)?.length ?? 0) === 0) {
			diagnostics.push({
				severity: ctx.strictly("warning"),
				code: "V003",
				message: `Process '${pid}' has no outputs`,
				range: zeroRange(),
			});
		}
	}
	return diagnostics;
}

/** V020: a process declared in front matter but absent from every edge (§15.10). */
export function orphanedProcess(ctx: RuleContext): Diagnostic[] {
	const diagnostics: Diagnostic[] = [];
	for (const pid of Object.keys(ctx.processMeta)) {
		if (!ctx.edgeProcesses.has(pid)) {
			diagnostics.push({
				severity: ctx.strictly("warning"),
				code: "V020",
				message: `Process '${pid}' is declared but has no edges (orphaned process)`,
				range: zeroRange(),
			});
		}
	}
	return diagnostics;
}
